name: prepare_config

on: workflow_dispatch

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Build Env
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo -E apt-get update > /dev/null
          sudo -E apt-get -y full-upgrade > /dev/null
          sudo -E apt-get -y autoremove --purge > /dev/null
          sudo -E apt-get clean > /dev/null
          sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Checkout
        uses: actions/checkout@main

      - name: Clone Source Code
        uses: actions/checkout@main
        with:
          repository: coolsnowwolf/lede
          path: openwrt

      - name: Update & Install Feeds
        working-directory: ./openwrt
        run: |
          echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> ./feeds.conf.default
          echo "src-git small https://github.com/kenzok8/small" >> ./feeds.conf.default
          chmod +x ./scripts/*
          ./scripts/feeds update -a > /dev/null
          ./scripts/feeds install -a > /dev/null

      - name: Configuration Apply
        env:
          CONFIG_FILE: "./lean/x86_64.config"
        run: |
          [ -e $CONFIG_FILE ] 
          cp $CONFIG_FILE openwrt/.config
          make defconfig

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main

      - name: Delete Workflow Runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
